
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Sadie.Game.Navigator"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "Sadie.API"

